# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PracticeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PracticeProject
    pod 'practiceProject',:path =>'../'

  target 'PracticeProjectTests' do
    inherit! :search_paths
  end

  target 'PracticeProjectUITests' do
    # Pods for testing
  end

end
